# Generated by Django 5.0 on 2024-01-02 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='confirmpassword',
        ),
    ]
