# Generated by Django 5.0 on 2024-01-03 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_user_email_alter_user_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserAuth',
        ),
    ]
