# Generated by Django 5.0 on 2024-04-16 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_receivedata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReceiveData',
        ),
    ]
