# Generated by Django 5.0 on 2024-01-02 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_register_confirmpassword'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='User',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
